### DISCUSSION TITLE
What exactly is needed for the S3 setup?

### DISCUSSION THREAD

**Discussion by Magicloud** [datashim-io/datashim#238] [Q&A]
I have a general private S3 bucket, and I want to try out mounting it as a volume to Kubernetes.

I have this dataset:

```
apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
metadata:
  name: xxx
spec:
  local:
    type: "COS"
    secret-name: "xxx"
    secret-namespace: "audit"
    endpoint: "https://s3.eu-west-3.amazonaws.com/abcde"
    bucket: "abcde"
    readonly: "true"
    region: "eu-west-3"
```

But the PVC is pending due to `failed to provision volume with StorageClass "csi-s3": rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8`.

I wonder if I need something set for the bucket, or the IAM permission. The secret has been tested, I can upload and download files.
