### DISCUSSION TITLE
Creating Datasets on bucket subpaths not work

### DISCUSSION THREAD

**Discussion by bin1st090104** [datashim-io/datashim#393] [Q&A] [answered]
I create 2 datasets like this:

``` yaml
apiVersion: datashim.io/v1alpha1
kind: Dataset
metadata:
  name: nginx-manager-conf
spec:
  local:
    bucket: toanbs-test
    endpoint: https://s3-sgn10.fptcloud.com
    secret-name: toanbs-test-bucket
    type: COS
    folder: /nginx-manager-conf
---
apiVersion: datashim.io/v1alpha1
kind: Dataset
metadata:
  name: nginx-conf
spec:
  local:
    bucket: toanbs-test
    endpoint: https://s3-sgn10.fptcloud.com
    secret-name: toanbs-test-bucket
    type: COS
    folder: /nginx-conf
```
I limit the subpaths are `/nginx-manager-conf` and `/nginx-conf`.
Then i create a pod to test.

``` yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  volumes:
  - name: nginx-manager-conf
    persistentVolumeClaim:
      claimName: nginx-manager-conf
  - name: nginx-conf
    persistentVolumeClaim:
      claimName: nginx-conf
  containers:
    - name: nginx-container
      image: nginx:alpine
      ports:
      - containerPort: 80
        name: http-server
      volumeMounts:
      - mountPath: /nginx-manager-conf
        name: nginx-manager-conf
      - mountPath: /nginx-conf
        name: nginx-conf
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
```

But when i connect to this pod, it still mount root directory:
![image](https://github.com/user-attachments/assets/e8e66e9c-6460-4ddb-83e7-57913c144292)
