### ISSUE TITLE
Throw errors for names containing illegal characters

### ISSUE THREAD

**Issue by YiannisGkoufas** [datashim-io/datashim#108]
As reported here https://github.com/datashim-io/datashim/issues/106
In dataset definitions like this:
```yaml
apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
metadata:
  name: kind-example-v0.2-try6-cp4d3f6d318f7c
spec:
  local:
    type: "COS"
    secret-name: "bucket-creds"
    secret-namespace: "m4d-system"
    endpoint: "http://s3.eu.cloud-object-storage.appdomain.cloud"
    provision: "true"
    bucket: "kind-example-v0.2-try6-cp4d3f6d318f7c"
```
there should be the necessary message in the dataset.status
FYI @shlomitk1
