### ISSUE TITLE
Unable to mount private s3 buckets

### ISSUE THREAD

**Issue by collinarnett** [datashim-io/datashim#111]
Hello,

I'm trying to mount a private s3 bucket and I'm running into trouble:

I'm currently applying the following yaml:

```
apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
metadata:
  name: test-dataset
spec:
  local:
    type: "COS"
    accessKeyID: "my_access_key"
    secretAccessKey: "my_secret_access_key"
    endpoint: "http://s3.us-east-1.amazonaws.com"
    bucket: "bucket"
    region: "" #it can be empty
```

This configuration works when the bucket is public, however when the bucket is private the provisioner is unable to find the bucket:
```
I0628 04:59:08.584849 1 controller.go:645] CreateVolume failed, supports topology = false, node selected false => may reschedule = false => state = Finished: rpc error: code = Unknown desc = s3 bucket: bucket does not exist
```

Nothing that I've read in the docs seems to suggest that private buckets are unable to work with datashim but I am probably doing something wrong.
