### ISSUE TITLE
Support URL-style bucket names in dataset definitions

### ISSUE THREAD

**Issue by srikumar003** [datashim-io/datashim#128]
There have been requests to allow datasets to be defined using the bucket urls and static web hosting formats. This means that the dataset definition would allow:

```
apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
metadata:
  name: example-dataset
spec:
  local:
    type: "COS"
   ...
    bucket: "https://<bucket_name>.<endpoint_url>"
```

without the need for specifying endpoint separately
