### ISSUE TITLE
Datasets and initContainers

### ISSUE THREAD

**Issue by seb-835** [datashim-io/datashim#157]
Hi Team,

can you confirm that Datasetś PVC are not mount in initContainers ?
Is it an option you can add ? or something you will never do ?

Best Regards

**Comment by srikumar003** [comment]
@seb-835 The PVCs created by Datashim are like any other, so they should work in initContainers. However, if you have come across a problem with using them, please provide a YAML example here and I'll check it out.

**Comment by seb-835** [comment]
@srikumar003 

I agree they can be attach to initContainer using the k8s way  with VolumeMount + Volume PersistentVolumeClaim declaration.
But using the DLF way with Labels, initcontainer does not have them mount.

If i apply the pod.yaml manifest :
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    dataset.0.id: nfs-rtfaas-job
    dataset.0.useas: mount
  name: busybox
  namespace: job-fn
spec:
  initContainers:
  - args:
    - /bin/sh
    - -c
    - sleep 120 
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    name: init
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 300
    image: busybox:latest
    name: main 
```
and then describe the pods running
```
Init Containers:
  init:
    Container ID:  docker://d78851d8a29d1a744b966a28a9f39fcf0f01990c7a037056e9e3e0d054fda090
    Image:          busybox:latest
    Args:
      /bin/sh
      -c
      sleep 120
    State:          Running
      Started:      Thu, 03 Feb 2022 13:03:12 +0000
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-rqdj4 (ro)
Containers:
  main:
    Container ID:  
    Image:         busybox:latest
    Args:
      /bin/sh
      -c
      sleep 300
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /mnt/datasets/nfs-rtfaas-job from nfs-rtfaas-job (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-rqdj4 (ro)

```
We can observe that the initcontainer have not the Mount : /mnt/datasets/nfs-rtfaas-job from nfs-rtfaas-job (rw).
