### ISSUE TITLE
The s3 bucket is not mounted into the pod according to the example.

### ISSUE THREAD

**Issue by fighterhit** [datashim-io/datashim#167]
- all component pods
```
root@ai-2080ti-27:~# kubectl get po -n dlf
NAME                               READY   STATUS    RESTARTS   AGE
csi-attacher-nfsplugin-0           2/2     Running   0          18h
csi-attacher-s3-0                  1/1     Running   0          18h
csi-controller-h3-0                3/3     Running   0          18h
csi-nodeplugin-h3-dj4sd            2/2     Running   0          18h
csi-nodeplugin-h3-k9nl9            2/2     Running   0          18h
csi-nodeplugin-nfsplugin-9frr2     2/2     Running   0          18h
csi-nodeplugin-nfsplugin-g6qxs     2/2     Running   0          18h
csi-provisioner-s3-0               1/1     Running   0          18h
csi-s3-gtbtr                       2/2     Running   0          18h
csi-s3-plstj                       2/2     Running   0          18h
dataset-operator-555468455-jfhzh   1/1     Running   0          18h
```

- my s3 bucket and content
```
xxx@ai-2080ti-27:~$ s3cmd ls s3://test
2022-04-13 06:25    272262854  s3://test/NVIDIA-Linux-x86_64-470.94.run
```

- s3 secret
```
apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
metadata:
  name: example-dataset
  namespace: danlu-efficiency
spec:
  local:
    type: "COS"
    accessKeyID: "xxx"  #accessKey
    secretAccessKey: "xxx"  #secretKey
    endpoint: "https://dev-ss3.xxx.xxxcom"
    bucket: "test"
    readonly: "false" # default is false
    region: "" #it can be empty
```

- generated configmap

```
root@ai-2080ti-27:~# kubectl -n danlu-efficiency get cm example-dataset 
NAME              DATA   AGE
example-dataset   3      61m
```

- generated pv/pvc
```
root@ai-2080ti-27:~# kubectl -n danlu-efficiency get   pvc
NAME              STATUS   VOLUME                                     CAPACITY       ACCESS MODES   STORAGECLASS   AGE
example-dataset   Bound    pvc-d76dd77a-83c3-45a6-9fe3-968d54e66289   9765625000Ki   RWX            csi-s3         63m
```

- nginx example
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: danlu-efficiency
  labels:
    dataset.0.id: "example-dataset"
    dataset.0.useas: "mount"
spec:
  containers:
    - name: nginx
      image: nginx
```

- There is nothing in the /mnt directory int the above nginx container.

```
root@ai-2080ti-27:~# kubectl -n danlu-efficiency exec nginx -- ls /mnt
root@ai-2080ti-27:~# 
```

**Comment by srikumar003** [comment]
@fighterhit can you please provide the kubernetes version and implementation (minikube, cloud service type, etc) ? Thanks!

**Comment by fighterhit** [comment]
> @fighterhit can you please provide the kubernetes version and implementation (minikube, cloud service type, etc) ? Thanks!

Thanks for your quick reply @srikumar003 .  My kubernetes cluster version is 1.18.3, which is manually built through `kubeadm`.

```
root@ai-2080ti-27:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by srikumar003** [comment]
@fighterhit  can you please try to mount the pvc without the dataset labels ? That is, try this pod definition

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: danlu-efficiency
  labels:
    dataset.0.id: "example-dataset"
    dataset.0.useas: "mount"
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: "/mount/dataset1"
           name: "dataset1"
  volumes:
    - name: dataset1
       persistentVolumeClaim:
       claimName: example-dataset
```
