### ISSUE TITLE
pod has unbound immediate PersistentVolumeClaims

### ISSUE THREAD

**Issue by Tazovsky** [datashim-io/datashim#197]
I installed datashim with `kubectl apply -f https://raw.githubusercontent.com/datashim-io/datashim/master/release-tools/manifests/dlf.yaml`

My object definitions are:

```
apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
metadata:
  name: example-dataset
spec:
  local:
    type: "COS"
    accessKeyID: "my.acceskey.id"
    secretAccessKey: "my.access.key"
    endpoint: "me.endpoint"
    bucket: "my-bucket"
    readonly: "true" # default is false
    region: "my.region"
```

```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        dataset.0.id: "example-dataset"
        dataset.0.useas: "mount"
    spec:
      volumes:
      - name: "example-dataset"
        persistentVolumeClaim:
          claimName: "example-dataset"
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        volumeMounts:
        - mountPath: "/mount/dataset1"
          name: "example-dataset"
        imagePullPolicy: IfNotPresent
        ports:
        - name: app-port
          containerPort: {{ .Values.service.containerPort }}
          protocol: TCP
```
but I'm facing following issue:

![image](https://user-images.githubusercontent.com/29068994/179040052-2d358292-4cf8-4093-96de-1334fd395ce3.png)

Can you help me with that issue?
