### ISSUE TITLE
Pod invalid: mountPath: invalid value must be unique.

### ISSUE THREAD

**Issue by cwichka** [datashim-io/datashim#207]
Hi,
We are having the following issue when creating pods labeled properly with the PVC names to be mounted.
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    dataset.0.id: gcp-test-a8310d134fb84c5e-inputs
    dataset.0.useas: mount
    dataset.1.id: gcp-test-a8310d134fb84c5e-outputs
    dataset.1.useas: mount
spec:
  containers:
    - name: nginx
      image: nginx
```

Error received:
```
kubectl apply -f pod.yaml 
The Pod "nginx" is invalid: spec.containers[0].volumeMounts[3].mountPath: Invalid value: "/mnt/datasets/gcp-test-a8310d134fb84c5e-inputs": must be unique

```

PVCs to be mounted are
```
gcp-test-a8310d134fb84c5e-inputs
gcp-test-a8310d134fb84c5e-outputs
```
However, when we try to mount them without using datashim, they get mounted properly
 ```
 apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - mountPath: /mnt/datasets/gcp-test-a8310d134fb84c5e-inputs
        name: gcp-test-a8310d134fb84c5e-inputs
      - mountPath: /mnt/datasets/gcp-test-a8310d134fb84c5e-outputs
        name: gcp-test-a8310d134fb84c5e-outputs
  volumes:
  - name: gcp-test-a8310d134fb84c5e-inputs
    persistentVolumeClaim:
      claimName: gcp-test-a8310d134fb84c5e-inputs
  - name: gcp-test-a8310d134fb84c5e-outputs
    persistentVolumeClaim:
      claimName: gcp-test-a8310d134fb84c5e-outputs

```
Please notice that we are deploying datashim chart we found [here](https://github.com/datashim-io/datashim/tree/master/chart) on the repo using helm and we are running on GKE v1.24.3-gke.2100

Mounting PVCs with the same pod spec works perfectly when deploying datashim from this [manifest](https://github.com/datashim-io/datashim/blob/v0.2.0/release-tools/manifests/dlf.yaml) and running on k8s v1.19
However, we wanted to upgrade the cluster to the latest k8s version and the same manifest not working on newer k8s versions (pod is up but without any mounted volumes)

Any idea what could have happened ?
