### ISSUE TITLE
storageClassName is not configurable for dataset

### ISSUE THREAD

**Issue by tcassaert** [datashim-io/datashim#208]
We were trying to evaluate what mounter would work best for our use case, the s3fs one or the goofys one. We deployed the datashim with the helm chart and following `values.yaml`:

```
global:
  dockerRegistrySecret: "" # leave empty if public repo
  baseRepo: "quay.io/datashim-io"
  arch: "amd64"
  type: "k8s"
  namespaceYaml: false

  sidecars:
    kubeletPath: "/var/lib/kubelet"
    baseRepo: "k8s.gcr.io/sig-storage"
    images:
      externalAttacher:
        image: "csi-attacher"
        tag: "v3.3.0"
      nodeDriverRegistrar:
        image: "csi-node-driver-registrar"
        tag: "v2.3.0"
      externalProvisioner:
        image: "csi-provisioner"
        tag: "v2.2.2"

csi-nfs-chart:
  enabled: false
# baseRepo: "anotherrepo"
# dockerRegistrySecret: "anothersecret"
  csinfs:
    image: "csi-nfs"
    tag: "latest"
  sidecars: {} # in case you want to force override regardless of the csi-nfs-chart/values.yaml

csi-s3-chart:
# baseRepo: "anotherrepo"
# dockerRegistrySecret: "anothersecret"
# mounter: "goofys"
  csis3:
    image: "csi-s3"
    tag: "latest"
  sidecars: {} # in case you want to force override regardless of the csi-s3-chart/values.yaml

csi-h3-chart:
  enabled: false
  baseRepo: "carvicsforth"
# dockerRegistrySecret: "anothersecret"
  csih3:
    image: "csi-h3"
    tag: "v1.2.0"
  sidecars: {}
dataset-operator-chart:
#  baseRepo: "quay.io/datashim"
# dockerRegistrySecret: "anothersecret"
  generatekeys:
    image: "generate-keys"
    tag: "latest"
  datasetoperator:
    image: "dataset-operator"
    tag: "latest"
```
which is the default, apart from disabling `nfs` and `h3`.

Then we deployed a dataset:

```
---
apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
metadata:
  name: eodata
  namespace: spark-jobs
spec:
  local:
    type: "COS"
    accessKeyID: "1234"
    secretAccessKey: "1234"
    endpoint: "http://example.com"
    bucket: "bucket"
    region: "Region"
```
This works fine and we can access the data in a pod that mounts the created PVC.

Now we also wanted to use the `s3fs` mounter. According to https://github.com/datashim-io/datashim/blob/master/src/csi-s3/README.md?plain=1#L98, we can create another StorageClass with another mounter, which we did. 

Now, there is no option to define another dataset, which defines the newly created StorageClass. The StorageClass seems hard-coded at https://github.com/datashim-io/datashim/blob/master/src/dataset-operator/controllers/datasetinternal_controller.go#L465. 

Is there another way to define what StorageClass the PVC should use?
