### ISSUE TITLE
Are multiple `dataset.<n>` pod labels supported?

### ISSUE THREAD

**Issue by starpit** [datashim-io/datashim#268]
does datashim support multiple `dataset.<n>` labels on a pod? i am seeing issues with the datashim mutating web hook. it seems to be doing something strange:

> The Pod “foo” is invalid: spec.containers[0].volumeMounts[3].mountPath: Invalid value: “/mnt/datasets/hap-models”: must be unique

```
apiVersion: v1
kind: Pod
metadata:
  name: foo
  labels:
    dataset.0.id: hap-xs
    dataset.0.useas: mount
    dataset.1.id: hap-models
    dataset.1.useas: mount
spec:
  containers:
    - name: foo
      image: ubuntu
      command: ["/bin/bash", "-c", "sleep infinity"]
```
