### ISSUE TITLE
feature: Support multiple `useas` modes for a dataset

### ISSUE THREAD

**Issue by srikumar003** [datashim-io/datashim#271]
Allow multiple useas modes for a single dataset (. e.g. the pod definition below
```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
    dataset.0.id: "tests3a"
    dataset.0.useas: "mount.configmap"
```
should lead to the dataset mounted in the volume as well as available as environment variables through config map injection
