### ISSUE TITLE
Pod in Pending state, NFS share not attaching

### ISSUE THREAD

**Issue by marhav20** [datashim-io/datashim#338]
Datashim version 0.3.0 (issue is the same with the latest master commit)
Installed via dlf.yaml (not helm)
Kubernetes 1.28.2 (plain cluster on a set of servers installed with kubeam)

A pod mounting a datashim NFS share remains in `Pending` state. Mounting the share natively on some Linux client works. So the issue does not seem to be the share. The event section of the pod reports:

`AttachVolume.Attach failed for volume "nfstest" : timed out waiting for external-attacher of csi-nfsplugin CSI driver to attach volume nfstest-60111c`.

In addition the log of the `csi-attacher-nfsplugin-0` reports (not sure if related):

`request.go:1181] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"volumeattachments.storage.k8s.io \"csi-0240b4292d16e45fca7e032917192981b560605cae04088ac16b8e2395dd796c\" is forbidden: User \"system:serviceaccount:dlf:csi-attacher-nfs\" cannot patch resource \"volumeattachments/status\" in API group \"storage.k8s.io\" at the cluster scope","reason":"Forbidden","details":{"name":"csi-0240b4292d16e45fca7e032917192981b560605cae04088ac16b8e2395dd796c","group":"storage.k8s.io","kind":"volumeattachments"},"code":403}`

The `csi-attacher-nfs` service account uses the `external-attacher-runner-nfs` clusterrole, which has the patch and update verbs configured:
```
kind: ClusterRole
metadata:
  ...
  name: external-attacher-runner-nfs
rules:
  ...
- apiGroups:
  - storage.k8s.io
  resources:
  - volumeattachments
  verbs:
  - get
  - list
  - watch
  - update
  - patch
```

The `PVC` and `PV` are bound. The datashim nfs manifest:
```
#apiVersion: datashim.io/v1alpha1
apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
metadata:
  name: "nfstest"
  namespace: "default"
spec:
  local:
    type: NFS
    server: "<ip masked>"
    share: "/export"
    createDirPVC: "false"
```

The pod manifest is as follows:
```
apiVersion: v1
kind: Pod
metadata:
  name: almalinux
  namespace: default
spec:
  containers:
  - name: almalinux
    image: almalinux:8.9
    imagePullPolicy: IfNotPresent
    tty: true
    stdin: true
    volumeMounts:
    - name: nfs
      mountPath: "/nfs"
  volumes:
  - name: nfs
    persistentVolumeClaim:
      claimName: nfstest
```

Any idea what the reason could be?

**Comment by srikumar003** [comment]
@marhav20, It seems you have run into the RBAC problem reported in #336. While a PR is forthcoming, please update the RBAC to give permission to `volumeattachments/status`

**Comment by marhav20** [comment]
@srikumar003 This seems to be something different. Please have a look at the ClusterRole I had listed. It has the `patch` verb set. So I'm wondering if something else is required in addition.
```
kind: ClusterRole
metadata:
  ...
  name: external-attacher-runner-nfs
rules:
  ...
- apiGroups:
  - storage.k8s.io
  resources:
  - volumeattachments
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  ```

**Comment by srikumar003** [comment]
@marhav20 Please try this RBAC:
```
kind: ClusterRole
metadata:
  ...
  name: external-attacher-runner-nfs
rules:
  ...
- apiGroups:
  - storage.k8s.io
  resources:
  - volumeattachments
  - volumeattachments/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
```
