### ISSUE TITLE
PVC keeps having status Pending

### ISSUE THREAD

**Issue by vmtuan12** [datashim-io/datashim#364]
My PVC is having status pending, and when the description is like the image below. Is it telling me that the bucket is invalid or something like that?
![image](https://github.com/datashim-io/datashim/assets/100104530/d6de11f2-f2c1-4b61-8f98-17d487e64101)
The dataset yaml of mine is:

```
apiVersion: v1
kind: Secret
metadata:
  name: s3secret
stringData:
  accessKeyID: "minioadmin"
  secretAccessKey: "minioadmin"
---
apiVersion: datashim.io/v1alpha1
kind: Dataset
metadata:
  name: example-dataset
spec:
  local:
    type: "COS"
    secret-name: "s3secret"
    secret-namespace: "dlf"
    endpoint: "http://<IP>:<port>"
    bucket: "/home/test-ds"
    region: ""
```
