### ISSUE TITLE
What is "remote" fields used for?

### ISSUE THREAD

**Issue by chengzhycn** [datashim-io/datashim#408]
Noticed that all the use cases in the wiki of the datasets only used the "local" fields. While I viewed the datasets' crd, there is a "remote" field and some others. Is these fields deprecated or have some other functionalities? 

```yaml
              extract:
                type: string
              format:
                type: string
              local:
                additionalProperties:
                  type: string
                description: Foo is an example field of Dataset. Edit dataset_types.go
                  to remove/update
                type: object
              remote:
                additionalProperties:
                  type: string
                type: object
              type:
                description: TODO temp definition for archive
                type: string
              url:
                type: string
```
