### ISSUE TITLE
Limit access to datasets to specific pods running specific images

### ISSUE THREAD

**Issue by YiannisGkoufas** [datashim-io/datashim#42]
Currenty the user can create a dataset like this:
```
apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
metadata:
  name: your-dataset
spec:
  local:
    type: "COS"
    accessKeyID: "{AWS_ACCESS_KEY_ID}"
    secretAccessKey: "{AWS_SECRET_ACCESS_KEY}"
    endpoint: "{S3_SERVICE_URL}"
    bucket: "{BUCKET_NAME}"
    region: "" #it can be empty
```

Then if they specify a pod like this:
```
apiVersion: v1
kind: Pod
metadata:
  name: simple-nginx
  labels:
    dataset.0.id: "your-dataset"
    dataset.0.useas: "configmap"
spec:
  containers:
    - name: nginx
      image: nginx
```

It will be mutated as follows:
```
    - configMapRef:
        name: your-dataset
      prefix: your-dataset_
    - prefix: your-dataset_
      secretRef:
        name: your-dataset
```
As a result the credentials would be available in the pod with the `your-dataset_` prefix as env variables.

However, there are scenarios where we only want authorized images to access the credentials and not any pod.

We are designing with @mrsabath how this could be achieved with https://github.com/IBM/trusted-service-identity and this issue will capture this process.

From the DLF perspective we need to upload to Vault the secrets once a Dataset is created. The key-values would look like this:
```
<cluster>/<namespace>/<dataset>/accessKeyID
<cluster>/<namespace>/<dataset>/secretAccessKey
....
```

Then we need to modify our admission controller would add the necessary labels to the user's pod which would allow TSI to check whether this pod can use these credentials or not. Ideally it should work as before and expose it as env variables:
```
<dataset>_accessKeyID = xxxxx
<dataset>_secretAccessKey = xxxx
```

In case the image is not authorized, the credentials should not be injected

**Comment by mrsabath** [comment]
What if your admission controller simply injects the following annotations into the user's pod:

```
      annotations:
        admission.trusted.identity/inject: "true"
        tsi.secrets: |
             - tsi.secret/name: "<dataset>_accessKeyID"
               tsi.secret/constraints: "region,images"
               tsi.secret/local-path: "tsi-secrets/<dataset>_accessKeyID"
             - tsi.secret/name: "<dataset>_secretAccessKey"
               tsi.secret/constraints: "region,images"
               tsi.secret/local-path: "tsi-secrets/<dataset>_secretAccessKey"
```
where the constraints are defined by the level of security to be imposed for this data set (e.g. only containers in specific region and from a specific image can access this data object)

And TSI would obtain the secrets from Vault and inject them to the user's container at the location specifed by  `tsi.secret/local-path`

What do you think @YiannisGkoufas ?
