### ISSUE TITLE
DLF labels are having conflicts with Istio sidecar Injection

### ISSUE THREAD

**Issue by Tomcli** [datashim-io/datashim#48]
When trying to deploy a pod with DLF labels inside an namespace with istio inject, I'm seeing the errors below. It looks like there's some conflicts between the DLF and istio mutation. 

```
The Pod "nginx" is invalid: spec.volumes[4].name: Duplicate value: "example-dataset"
```

Here is my pod
```shell
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
  labels:
    dataset.0.id: "example-dataset"
    dataset.0.useas: "mount"
spec:
  containers:
    - name: nginx
      image: nginx
EOF
```

**Comment by YiannisGkoufas** [comment]
Hi @Tomcli can you try creating the pod like this:
```yaml
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    sidecar.istio.io/inject: "false"
  namespace: default
  labels:
    dataset.0.id: "example-dataset"
    dataset.0.useas: "mount"
spec:
  containers:
    - name: nginx
      image: nginx
EOF
```
