### ISSUE TITLE
Support H3 as an additional dataset type

### ISSUE THREAD

**Issue by chazapis** [datashim-io/datashim#59]
[H3](https://github.com/CARV-ICS-FORTH/H3) is an embedded High speed, High volume, and High availability object store, backed by a high-performance key-value store (RocksDB, Redis, etc.). H3 also provides a FUSE implementation to allow object access using file semantics. The [CSI H3 mount plugin](https://github.com/CARV-ICS-FORTH/csi-h3) (csi-h3 for short), allows you to use H3 FUSE for implementing persistent volumes in Kubernetes.

In practice, csi-h3 implements a fast and efficient filesystem on top of a key-value store. With csi-h3 deployed, and a Redis server running, you just need to specify the Redis endpoint and the bucket name you want to use, in order to get a mountpoint for your containers. H3 is embedded in csi-h3, so there are no other requirements to install.

H3 could be supported In DLF, with a dataset definition like the following:

```yaml
apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
metadata:
  name: example-dataset
spec:
  local:
    type: "H3"
    storageUri: "redis://redis.default.svc:6379"
    bucket: "b1"
```

Note that H3 supports many additional key-value stores, but in the distributed environment of Kubernetes, you need a key-value store that can be accessed through a network protocol. For persistent storage, [Ardb](https://github.com/yinqiwen/ardb) provides Redis connectivity over a range of key-value implementations, including RocksDB, LevelDB, and others. In that case, the `storageUri` used will still be in the form `redis://...`, but the actual service will be provided by Ardb.
