### ISSUE TITLE
Dataset labels not working for deployments

### ISSUE THREAD

**Issue by chazapis** [datashim-io/datashim#88]
When I use a dataset label to mount a dataset to a deployment, nothing happens.

Upon further inspection, it looks like the `MutatingWebhookConfiguration` does not trigger for `deployments`, but only for `pods`. For deployments, the `mutate` function should do exactly the same changes it does for pods, but work on the `/spec/template/spec` path instead of `/spec`.

**Comment by 5cat** [comment]
I have the same issue,

I used `PVC` instead of labels although [it is not recommended](https://github.com/datashim-io/datashim/discussions/218), it is what is working for deployments.

**Comment by ilvez** [comment]
I don't know about this, for me it worked (only relevant code of deployment description):
```yaml
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    metadata:
      labels:
        dataset.0.id: "example-dataset"
        dataset.0.useas: "mount"
```

Tested it first out with pod as an example, and then added `dataset` labels into deployment description.
