### ISSUE TITLE
error 400 Bad Request

### ISSUE THREAD

**Issue by ludzzz** [datashim-io/datashim#94]
Hi all,

I have a Kubernetes cluster on AWS (EKS).
we are currently using some workaround (script at the init of a node) to be able to mount s3 bucket on pod.

I tried to use datashim which looks very promising.
I installed the setup with https://raw.githubusercontent.com/IBM/dataset-lifecycle-framework/master/release-tools/manifests/dlf.yaml

here my dataset config:
```
apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
metadata:
  name: archive-dataset
spec:
  local:
    type: "COS"
    accessKeyID: "XXX"
    secretAccessKey: "XXX"
    endpoint: "https://s3.amazonaws.com"
    bucket: "bucket_name-ap-east-1"
    region: "ap-east-1" 
```

But I end up with the error:
```
  Warning  ProvisioningFailed    3m11s (x9 over 7m32s)  ch.ctrox.csi.s3-driver_csi-provisioner-s3-0_0ef0ce8b-2b1e-4a4e-8ebd-a82731d7ae1b  failed to provision volume with StorageClass "csi-s3": rpc error: code = Unknown desc = failed to check if bucket bucket_name-ap-east-1 exists: 400 Bad Request
```

All the pod in `dlf` namespace are running fine (`Running` status, I didn't dig the log yet)
I tried with different credentials.
I can mount successfully the bucket locally with `s3fs` or `goofys` (with the same credentials).

Did I miss anything?
Thank you very much for your work.

**Comment by YiannisGkoufas** [comment]
Hi @ludzzz thanks for your comments and reporting this issue.
Would you mind deleting the dataset and recreating using the following endpoint?
```
apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
metadata:
  name: archive-dataset
spec:
  local:
    type: "COS"
    accessKeyID: "XXX"
    secretAccessKey: "XXX"
    endpoint: "https://s3.ap-east-1.amazonaws.com"
    bucket: "bucket_name-ap-east-1"
```
Also it seems that `region` is not needed in Amazon S3, so you can remove it.
Let me know if it works!
